name: Create Tag and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.1)'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="v${{ github.event.inputs.version }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
          generate_release_notes: true
