name: Pre-commit CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
      id: precommit
      continue-on-error: true

    - name: Push changes if needed
      if: failure()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Apply pre-commit fixes"
        git push origin ${{ github.ref }}
      continue-on-error: true

    - name: Create a new Pull Request
      if: github.ref == 'refs/heads/main' && steps.precommit.outcome == 'failure'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: auto/pre-commit-fixes  # A new branch for the fixes
        commit-message: "Pre-commit fixes"
        title: "Pre-commit fixes"
        body: "This PR applies automatic pre-commit fixes."
        base: main
        delete-branch: true
