name: Pre-commit CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_TOKEN}}

    - uses: actions/setup-python@v3

    - uses: pre-commit/action@v3.0.1
      continue-on-error: true

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: fix: Automated Change
        branch: fix/pre-commit-auto
        create_branch: true
   