name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
      id: precommit
      continue-on-error: trues

    - name: Add a comment to the PR
      if: failure() && github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Pre-commit checks have failed. Please review and fix the following issues:
          ${{ steps.precommit.outputs.stdout }}

    - name: Push changes if needed
      if: failure()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Apply pre-commit fixes"
        git push origin ${{ github.ref }}
      continue-on-error: true
