name: Pre-commit CI
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_TOKEN}}

    - uses: actions/setup-python@v3

    - uses: pre-commit/action@v3.0.1
      continue-on-error: true

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "fix: Automated Changes by Pre-commit"
