name: Update from Template Repo

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch template repository
        run: |
          git remote add template https://github.com/duyl97/github-repo-template.git
          git fetch template
          git merge template/main --allow-unrelated-histories

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: ✨ Update from template repository
          title: ✨ Update from template repository
          body: Automated update from the template repository.
          branch: update-from-template
